import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://mortrack.app/auth/login');
  await page.locator('input[name="email"]').fill('m');
  await page.locator('input[name="email"]').click();
  await page.locator('input[name="email"]').fill('quality.assurance@mortrack.com13');
  await page.locator('input[name="password"]').click();
  await page.locator('input[name="password"]').fill('2');
  await page.locator('input[name="email"]').click();
  await page.locator('input[name="email"]').click();
  await page.locator('input[name="email"]').click();
  await page.locator('input[name="email"]').click();
  await page.locator('input[name="email"]').press('ArrowRight');
  await page.locator('input[name="email"]').press('ArrowDown');
  await page.locator('input[name="email"]').fill('quality.assurance@mortrack.com');
  await page.locator('input[name="password"]').click();
  await page.locator('input[name="password"]').fill('1324$leF');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByRole('link', { name: 'Return to Application' }).click();
  await page.getByRole('link', { name: '' }).click();
  await page.getByRole('textbox', { name: 'REMOVAL LOCATION' }).click();
  await page.getByRole('textbox', { name: 'REMOVAL LOCATION' }).click();
  await page.getByRole('textbox', { name: 'REMOVAL LOCATION' }).fill('123');
  await page.getByRole('button', { name: 'COUNTRY*' }).click();
  await page.locator('#list-item-374-0').getByText('United States').click();
  await page.locator('div').filter({ hasText: /^ADDRESS\*$/ }).click();
  await page.getByRole('textbox', { name: 'ADDRESS*' }).fill('123 main st');
  await page.getByRole('textbox', { name: 'CITY*' }).click();
  await page.getByRole('textbox', { name: 'CITY*' }).fill('city');
  await page.getByRole('textbox', { name: 'STATE*' }).click();
  await page.getByText('Alabama').click();
  await page.getByRole('textbox', { name: 'ZIP*' }).click();
  await page.getByRole('textbox', { name: 'ZIP*' }).fill('1234567');
});